In [114]:
s = "aabbaccc"

In [77]:
s = s + '0'
temp = []
cnt = 1
dic = {}

for i in range(len(s)-1):
    if s[i] == s[i+1]:
        cnt+=1
    else:
        temp.append(str(cnt))
        temp.append(s[i])
        cnt = 1
temp = filter(lambda a: a != '1', temp)
''.join(temp)
# answer = 0

'2a2ba3c'

In [307]:
s = "abcabcdede"

s = s + '0'
cnt = 1
dic = {}

for i in range(int(len(s)/2),0,-1):
    dic['len'+str(i)] = []
    
for i in range(int(len(s)/2),0,-1):
    ifcnt = 0
    for j in range(int((len(s)-1)/i)):
        
        if s[i*j:(j+1)*i] == s[(j+1)*i:(j+2)*i]:

            cnt+=1
            ifcnt += 1
        elif ifcnt == 0:
            break
            
        else:
            print('else',s[i*j:(j+1)*i], '=', s[(j+1)*i:(j+2)*i])
            dic['len'+str(i)].append(str(cnt))
            dic['len'+str(i)].append(s[i*j:(j+1)*i])
            cnt = 1
            if len(s[(j+1)*i:-1])<i:
                dic['len'+str(i)].append(s[(j+1)*i:-1])

    if ifcnt != 0:       
        dic['len'+str(i)] = list(filter(lambda a: a != '1', dic['len'+str(i)]))
        dic['len'+str(i)] = ''.join(dic['len'+str(i)])

strlen = {}
for i in dic.values():
    strlen[len(i)] = i
del strlen[0]


if len(strlen) == 0:
    answer = len(s)-1
else:
    answer = min(strlen.keys())

0
0
abcdede
else abc = ded
dede
else ded = e0
e
1
0
0


In [308]:
dic

{'len5': [], 'len4': [], 'len3': '2abcdede', 'len2': [], 'len1': []}

In [292]:
s[(j+2)*i:]

TypeError: slice indices must be integers or None or have an __index__ method

In [278]:
if min(strlen.keys()) == 'empty':
    print(len(s))

In [280]:
len(strlen.keys())

1

In [245]:
strlen[min(strlen.keys())]

'2ababcdcd'

In [235]:
value

['2ababcdcd', '2ab2cd2ab2cd']

In [236]:
max(value)

'2ababcdcd'

In [294]:
answer

14

In [255]:
dic

{'len5': [], 'len4': [], 'len3': '2abcded', 'len2': [], 'len1': []}

In [224]:
len(min(value))

12

In [231]:
dic.values()

dict_values(['2ababcdcd', [], [], [], [], [], '2ab2cd2ab2cd', []])

In [257]:
len("xababcdcdababcdcd")

17

In [287]:
strlen = {}
len(strlen)

0

In [309]:
x = "(()())()"

In [310]:
if '()' in x:
    print('y')

y


In [317]:
for i in range(len(x)):
    if x[i] == '(':
        if x[i+1] == ')':
            v =  
    
    

(
(
(
(


In [321]:
import numpy as np

In [322]:
key = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 1]])
lock = np.array([[1, 1, 1], [1, 1, 0], [1, 0, 1]])

In [326]:
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]
lock = [[1, 1, 1], [1, 1, 0], [1, 0, 1]]

In [496]:
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]
lock = [[1, 1, 1], [1, 1, 0], [1, 0, 1]]

m = len(key)
n = len(lock)
pattern = [(i,j.index(0)) for i,j in enumerate(lock) if 0 in j]
pattern_size = np.array(pattern).shape
scanner = np.array(pattern) - min(min(pattern))
npkey = np.array(key)

for i in range(4):
    print(i)
    for i in range(0,m-pattern_size[0] + 1,1):
        for j in range(0,m-pattern_size[0] + 1,1):
            temp = np.array((npkey[i][0:scanner.shape[0]],npkey[i+1][0:scanner.shape[1]]))
            z = scanner - temp
            if 1 not in z and -1 not in z:
                answer = True
                break
            print(z)
    for i in range(len(scanner[0])):
            scanner[i] = [scanner[i][j] for j in range(len(scanner)-1,-1,-1)]

# for i in range(len(scanner[0])):
#     scanner[i] = [scanner[i][j] for j in range(len(scanner)-1,-1,-1)]
# for i in range(0,m-pattern_size[0] + 1,1):
#     for j in range(0,m-pattern_size[0] + 1,1):
#         temp = np.array((npkey[i][0:scanner.shape[0]],npkey[i+1][0:scanner.shape[1]]))
#         z = scanner - temp
#         if 1 not in z & -1 not in z:
#             answer = True    
#         print(z)

# for i in range(len(scanner[0])):
#     scanner[i] = [scanner[i][j] for j in range(len(scanner)-1,-1,-1)]
# for i in range(0,m-pattern_size[0] + 1,1):
#     for j in range(0,m-pattern_size[0] + 1,1):
#         temp = np.array((npkey[i][0:scanner.shape[0]],npkey[i+1][0:scanner.shape[1]]))
#         z = scanner - temp
#         if 1 not in z & -1 not in z:
#             answer = True    
#         print(z)

# for i in range(len(scanner[0])):
#     scanner[i] = [scanner[i][j] for j in range(len(scanner)-1,-1,-1)]
# for i in range(0,m-pattern_size[0] + 1,1):
#     for j in range(0,m-pattern_size[0] + 1,1):
#         temp = np.array((npkey[i][0:scanner.shape[0]],npkey[i+1][0:scanner.shape[1]]))
#         z = scanner - temp
#         if 1 not in z & -1 not in z:
#             answer = 'True'
            
#         print(z)
    
print(answer)

0
[[0 1]
 [0 0]]
[[0 1]
 [0 0]]
[[-1  1]
 [ 1 -1]]
[[-1  1]
 [ 1 -1]]
1
[[ 1  0]
 [-1  1]]
[[ 1  0]
 [-1  1]]
2
[[0 1]
 [0 0]]
[[0 1]
 [0 0]]
[[-1  1]
 [ 1 -1]]
[[-1  1]
 [ 1 -1]]
3
[[ 1  0]
 [-1  1]]
[[ 1  0]
 [-1  1]]
True


In [487]:
type(z)

numpy.ndarray

In [492]:
if 1 not in z and -1 not in z:
    print('y')

y


In [465]:
cs = [[0]*len(scanner[0]) for i in range(len(scanner))]

In [480]:
for i in range(len(cs[0])):
    cs[i] = [cs[i][j] for j in range(len(cs)-1,-1,-1)]
    print(cs[i])

[1, 0]
[0, 1]


In [478]:
cs

[[1, 0], [0, 1]]

In [470]:
scanner

array([[0, 1],
       [1, 0]])

In [447]:
cscanner = scanner
cscanner[:][0] = scanner[0][:]
cscanner[:][0] = scanner[0][:]

In [458]:
cscanner = np.array([np.transpose(scanner[0]),np.transpose(scanner[1].T)])

In [460]:
scanner[:,0]

array([0, 1])

In [ ]:
cscanner

In [459]:
cscanner

array([[0, 1],
       [1, 0]])

In [449]:
scanner

array([[0, 1],
       [1, 0]])

In [443]:
cscanner

array([[0, 1],
       [1, 0]])

In [423]:
z = scanner - temp

In [434]:
if 1 not in scanner & -1 not in scanner:
    print(scanner)

In [348]:
print(np.array([(1, 2, 0), (2, 1, 0)]))

[[1 2 0]
 [2 1 0]]


In [353]:
for i in range(3,6,-1):
    print(i)

In [361]:
list(np.array(pattern) - min(min(pattern)))

[array([0, 1]), array([1, 0])]

In [362]:
scanner = np.array(pattern) - min(min(pattern))

In [365]:
scanner[0+i][0]

0

In [366]:
scanner

array([[0, 1],
       [1, 0]])

In [387]:
npkey = np.array(key)

In [386]:
np.array(key)[0][0:2],np.array(key)[1][0:2]

(array([0, 0]), array([1, 0]))

In [397]:
print(npkey[0][0:2],npkey[1][0:2])

[0 0] [1 0]


In [412]:
temp = np.array((npkey[0][0:scanner.shape[0]],npkey[1][0:scanner.shape[1]]))

In [408]:
type(temp)

numpy.ndarray

In [411]:
scanner - temp

array([[0, 1],
       [0, 0]])

In [497]:
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]
lock = [[1, 1, 1], [1, 1, 0], [1, 0, 1]]

m = len(key)
n = len(lock)
pattern = [(i,j.index(0)) for i,j in enumerate(lock) if 0 in j]
pattern_size = np.array(pattern).shape
scanner = np.array(pattern) - min(min(pattern))
npkey = np.array(key)

for i in range(0,m-pattern_size[0] + 1,1):
    for j in range(0,m-pattern_size[0] + 1,1):
        temp = np.array((npkey[i][0:scanner.shape[0]],npkey[i+1][0:scanner.shape[1]]))
        z = scanner - temp
        if 1 not in z and -1 not in z:
            answer = True
            break
        
for i in range(len(scanner[0])):
        scanner[i] = [scanner[i][j] for j in range(len(scanner)-1,-1,-1)]

for i in range(0,m-pattern_size[0] + 1,1):
    for j in range(0,m-pattern_size[0] + 1,1):
        temp = np.array((npkey[i][0:scanner.shape[0]],npkey[i+1][0:scanner.shape[1]]))
        z = scanner - temp
        if 1 not in z and -1 not in z:
            answer = True
            break

for i in range(len(scanner[0])):
    scanner[i] = [scanner[i][j] for j in range(len(scanner)-1,-1,-1)]
for i in range(0,m-pattern_size[0] + 1,1):
    for j in range(0,m-pattern_size[0] + 1,1):
        temp = np.array((npkey[i][0:scanner.shape[0]],npkey[i+1][0:scanner.shape[1]]))
        z = scanner - temp
        if 1 not in z and -1 not in z:
            answer = True
            break

for i in range(len(scanner[0])):
    scanner[i] = [scanner[i][j] for j in range(len(scanner)-1,-1,-1)]
for i in range(0,m-pattern_size[0] + 1,1):
    for j in range(0,m-pattern_size[0] + 1,1):
        temp = np.array((npkey[i][0:scanner.shape[0]],npkey[i+1][0:scanner.shape[1]]))
        z = scanner - temp
        if 1 not in z and -1 not in z:
            answer = True
            break
    
print(answer)

[[0 1]
 [0 0]]
[[0 1]
 [0 0]]
[[-1  1]
 [ 1 -1]]
[[-1  1]
 [ 1 -1]]
[[ 1  0]
 [-1  1]]
[[ 1  0]
 [-1  1]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 1]
 [0 0]]
[[0 1]
 [0 0]]
[[-1  1]
 [ 1 -1]]
[[-1  1]
 [ 1 -1]]
True


In [ ]:
import numpy as np
def solution(key, lock):

    pattern = [(i,j.index(0)) for i,j in enumerate(lock) if 0 in j]
    scanner = np.array(pattern) - min(min(pattern))
    npkey = np.array(key)

    for i in range(4):
        for i in range(0,len(key)-np.array(pattern).shape[0] + 1,1):
            for j in range(0,len(key)-np.array(pattern).shape[0] + 1,1):
                temp = np.array((npkey[i][0:scanner.shape[0]],npkey[i+1][0:scanner.shape[1]]))
                
                if 1 not in scanner - temp and -1 not in scanner - temp:
                    answer = True
                    break
        for i in range(len(scanner[0])):
                scanner[i] = [scanner[i][j] for j in range(len(scanner)-1,-1,-1)]
    

    return answer

In [502]:
min(min(pattern))

1

In [510]:
board = np.array([[0, 0, 0, 1, 1],[0, 0, 0, 1, 0],[0, 1, 0, 1, 1],[1, 1, 0, 0, 1],[0, 0, 0, 0, 0]])
x1 = 0
y1 = 0
x2 = 0
y2 = 1
bot = np.array([(x1,y1),(x2,y2)])

In [504]:
print(np.array(board))

[[0 0 0 1 1]
 [0 0 0 1 0]
 [0 1 0 1 1]
 [1 1 0 0 1]
 [0 0 0 0 0]]


In [531]:
x1 = 0
y1 = 0
x2 = 0
y2 = 1

for i in range(board.shape[0]):
    if board[i][0] == 0 and board[i][1] == 0:
        x1 += 1
        x2 += 1
        continue
    else:
        x1 -=1
        x2 -=1
        break
print([(x1,y1),(x2,y2)])
for i in range(board.shape[1]):
    if board[x][i] == 0 and board[x][i+1] == 0:
        y1 += 1
        y2 += 1
        continue
    else:
        y1 -= 1
        y2 -= 1
        break
print([(x1,y1),(x2,y2)])
bot = np.array([(x1,y1),(x2,y2)])
print(bot)

[(1, 0), (1, 1)]
[(1, -1), (1, 0)]
[[ 1 -1]
 [ 1  0]]
