마방진 그리기

In [24]:
import numpy as np

In [185]:
magic = np.zeros([5,5])
# init[0][2] = 1

In [186]:
magic

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [187]:
j= 0
k = 0
for i in range(25):
    magic[(5-i+j)%5][(2+i-k)%5] = i+1
    if (i+1)%5 == 0:
        j+=2
        k+=1

In [188]:
magic

array([[17., 24.,  1.,  8., 15.],
       [23.,  5.,  7., 14., 16.],
       [ 4.,  6., 13., 20., 22.],
       [10., 12., 19., 21.,  3.],
       [11., 18., 25.,  2.,  9.]])

달팽이 수열
-> 수학적 규칙을 찾아서 풀려했으나 실패
-> 리스트로 방향키를 만들어서 사용하는 법 배움
-> 패딩을 사용하는 법에 대해 배움

In [397]:
snail = np.zeros([5,5])

In [375]:
snail

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [465]:
snail = np.zeros([6,6])
x0,y0 = 0,0
j,k = 0,1
T=5
t=5
f = 0
cnt0 = 1
for i in range(25):
    cnt = i+cnt0
    x = x0+j*((i+1)%5)
    y = y0 + k*(i%5)
    print(i,cnt,T,f,x,y)
    snail[x][y] = i+1
    if (cnt)%T==0:
        print('ha')
        f+=1
        y0 = y
        x0  = x
        j,k = k,j
        if f%2 == 1:
            T=T-1
            cnt0-=1
        if f%2 ==0:
            print('haha')
            j,k = -j,-k

0 1 5 0 0 0
1 2 5 0 0 1
2 3 5 0 0 2
3 4 5 0 0 3
4 5 5 0 0 4
ha
5 5 4 1 1 4
6 6 4 1 2 4
7 7 4 1 3 4
8 8 4 1 4 4
ha
haha
9 9 4 2 4 0
10 10 4 2 4 4
11 11 4 2 4 3
12 12 4 2 4 2
ha
13 12 3 3 0 2
ha
haha
14 13 3 4 0 6


IndexError: index 6 is out of bounds for axis 0 with size 6

In [476]:
#direction, padding 쓰고 싶은 배열의 겉을 안쓰는 숫자로 채움
dx = [0,1,0,-1]
dy = [1,0,-1,0]

In [533]:
# 인덱스가 사용하고 싶은 배열의 밖으로 나갔을 때 오류가 발생하지 않게 해줌
# 사용하지 않는 숫자로 padding 해주면 배열 밖이라는 것을 컴퓨터에게 인식시켜줄 수 있다.
pad = np.zeros([7,7])
pad[0] = -1
pad[:,0] = -1
pad[-1] = -1
pad[:,-1] = -1

In [534]:
x,y = 1,1
dx = [0,1,0,-1]
dy = [1,0,-1,0]
dirt = 0
for i in range(25):
    pad[x,y] = i+1
    print(x,y)
    x = x+dx[dirt%4]
    y = y+dy[dirt%4]
    
    if pad[x,y] !=0: #벽에 부딪히면
        x = x-dx[dirt%4]
        y = y-dy[dirt%4]
        dirt+=1
        x = x+dx[dirt%4]
        y = y+dy[dirt%4]

1 1
1 2
1 3
1 4
1 5
2 5
3 5
4 5
5 5
5 4
5 3
5 2
5 1
4 1
3 1
2 1
2 2
2 3
2 4
3 4
4 4
4 3
4 2
3 2
3 3


In [535]:
pad

array([[-1., -1., -1., -1., -1., -1., -1.],
       [-1.,  1.,  2.,  3.,  4.,  5., -1.],
       [-1., 16., 17., 18., 19.,  6., -1.],
       [-1., 15., 24., 25., 20.,  7., -1.],
       [-1., 14., 23., 22., 21.,  8., -1.],
       [-1., 13., 12., 11., 10.,  9., -1.],
       [-1., -1., -1., -1., -1., -1., -1.]])